# # This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# # For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

# name: Build & Deploy development application

# on:
#   push:
#     branches: [develop]

# jobs:
#   build_docker_image:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#         name: Check out code

#       - uses: mr-smithers-excellent/docker-build-push@v5
#         name: Build & push Docker image
#         with:
#           image: ghcr.io/khilltech/ikibina-api-dev
#           tags: v1, latest
#           registry: ghcr.io
#           dockerfile: Dockerfile.dev
#           username: ${{ secrets.GHCR_USERNAME }}
#           password: ${{ secrets.GHCR_TOKEN }}

#   deploy_to_dev_environment:
#     needs: build_docker_image
#     runs-on: ubuntu-latest
#     # strategy:
#     #   matrix:
#     #     node-version: [14.18.1]
#     # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

#     steps:
#       # - uses: actions/checkout@v2
#       # - name: Use Node.js ${{ matrix.node-version }}
#       #   uses: actions/setup-node@v2
#       #   with:
#       #     node-version: ${{ matrix.node-version }}
#       #     cache: 'yarn'
#       - run: echo "Supposed to deploy here..."
